"""phase3: 建知识库/文档等业务表

Revision ID: b7b94ea4a7c3
Revises: 
Create Date: 2026-08-01 23:10:32.611248+08:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7b94ea4a7c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='操作人'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型: upload/delete/query/create等'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='资源类型: document/kb/user'),
    sa.Column('resource_id', sa.BigInteger(), nullable=True, comment='资源ID'),
    sa.Column('detail', sa.Text(), nullable=True, comment='操作详情(JSON)'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='操作IP'),
    sa.Column('created_at', sa.String(length=30), nullable=False, comment='操作时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_bases',
    sa.Column('name', sa.String(length=200), nullable=False, comment='知识库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='创建者'),
    sa.Column('embedding_model', sa.String(length=100), nullable=False, comment='Embedding 模型'),
    sa.Column('chunk_size', sa.Integer(), nullable=False, comment='分块大小(tokens)'),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False, comment='分块重叠(tokens)'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='是否公开'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='用户'),
    sa.Column('kb_id', sa.BigInteger(), nullable=True, comment='关联知识库'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='对话标题'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('kb_id', sa.BigInteger(), nullable=False, comment='所属知识库'),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='原始文件名'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='pdf/docx/xlsx/md/txt'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小(bytes)'),
    sa.Column('storage_path', sa.String(length=1000), nullable=False, comment='存储路径'),
    sa.Column('chunk_count', sa.Integer(), nullable=False, comment='分块数量'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus'), nullable=False, comment='处理状态'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='失败原因'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False, comment='所属对话'),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False, comment='user/assistant/system'),
    sa.Column('content', mysql.LONGTEXT(), nullable=False, comment='消息内容'),
    sa.Column('tokens_used', sa.Integer(), nullable=False, comment='Token 消耗'),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False, comment='处理耗时(ms)'),
    sa.Column('created_at', sa.String(length=30), nullable=False, comment='创建时间字符串'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_citations',
    sa.Column('message_id', sa.BigInteger(), nullable=False, comment='所属消息'),
    sa.Column('document_id', sa.BigInteger(), nullable=True, comment='引用文档'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='分块索引'),
    sa.Column('score', sa.Float(), nullable=False, comment='相关度分数'),
    sa.Column('cited_text', sa.Text(), nullable=True, comment='引用原文片段'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_citations')
    op.drop_table('messages')
    op.drop_table('documents')
    op.drop_table('conversations')
    op.drop_table('knowledge_bases')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
