"""phase7_members_softdel_config

Revision ID: 253b415ce0a3
Revises: b7b94ea4a7c3
Create Date: 2026-08-04 15:15:55.259499+08:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253b415ce0a3'
down_revision: Union[str, None] = 'b7b94ea4a7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键'),
    sa.Column('value', sa.String(length=500), nullable=False, comment='配置值(字符串)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='说明'),
    sa.Column('updated_at', sa.String(length=30), nullable=False, comment='更新时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('kb_members',
    sa.Column('kb_id', sa.BigInteger(), nullable=False, comment='知识库'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='成员'),
    sa.Column('role', sa.Enum('VIEWER', 'EDITOR', 'OWNER', name='kbmemberrole'), nullable=False, comment='角色'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'user_id', name='uq_kb_member')
    )
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记'))
    op.add_column('documents', sa.Column('deleted_at', sa.String(length=30), nullable=True, comment='删除时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'is_deleted')
    op.drop_table('kb_members')
    op.drop_table('system_configs')
    # ### end Alembic commands ###
